apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: famous-quote
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-application
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
