apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: prometheus-deployment-02
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: prometheus
  template: 
    metadata:
      labels:
        app: prometheus
    spec: 
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus@sha256:075b1ba2c4ebb04bc3a6ab86c06ec8d8099f8fda1c96ef6d104d9bb1def1d8bc
        ports:
        - containerPort: 9090 
