apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-cp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: myapp.lab.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-cp-service
            port:
              number: 80

