apiVersion: v1
kind: LimitRange
metadata:
   name: my-limit-range-name
spec: 
  limits:
  - type: Pod
    max: 
      cpu: "200m"
      memory: "1500Mi"
    min:
      cpu: "50m"
      memory: "1024Mi"
  - type: Container 
    max: 
      cpu: "200m"
      memory: "1500Mi"
    min:
      cpu: "50m"
      memory: "1024Mi"
    defaultRequest:
      cpu: "70m"
      memory: "1030Mi"     
