apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-stable
spec:
  replicas: 9  # 90% traffic
  selector:
    matchLabels:
      app: nginx
      version: stable
  template:
    metadata:
      labels:
        app: nginx
        version: stable
    spec:
      containers:
      - name: nginx
        #image: nginx:1.18.0  #
        image: nginx:1.17.1 # Stable 
        ports:
        - containerPort: 80
