apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx  # No Version specified to include both deployemts [stable & canary]
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
