apiVersion: apps/v1
kind: Deployment
metadata:
  name: famous-quote
spec:
  replicas: 2
  selector:
    matchLabels:
      app: famous-quote
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: famous-quote
        image: example/web-app:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 1
