apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
    version: blue  # Initial setup to blue
    #version: green  # Upgrade setup to Green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
