apiVersion: v1
kind: Service
metadata:
  name: nginx-cip-np-service 
spec: 
  selector:
    app: nginx-cip
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001 
  type: NodePort
