FROM ubi8/ubi:8.5
MAINTAINER Chandra Prakash <binbash1807@gmail.com>
LABEL description="example image for demo"
RUN yum install -y httpd && \
    yum clean all
RUN echo "Hello from Containerfile" > /var/www/html/index.html 
EXPOSE 80 
ENTRYPOINT ["httpd"]
CMD ["-D" , "FOREGROUND" ]


