apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-persistent-storage
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/kubedata/statefulset
    server: 172.25.231.145
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
